# Default configuration
command qsub -V -l hostname=b20
option name=* -N $0
option time=* -l h_rt=$0
option mem=* -l h_vmem=$0
option mem=0
option num_threads=* -pe smp $0
option num_threads=1 -pe smp 1
option num_nodes=* -l nodes=$0
default gpu=0
option gpu=0 -q cpu.q
option gpu=* -q gpu.q -l gpu=$0 -pe smp $0  # Allocate more CPU than or equal to the number of GPUs

# Default node list
default nodelist=b20
option nodelist=* -l hostname=$0
